apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: agrxhlsic-python
  janus-idp.io/tekton: agrxhlsic-python
  backstage.io/kubernetes-id: agrxhlsic-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: agrxhlsic-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
